name: github pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 22 + Cache deps
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential python3

      - name: Print Node and Yarn versions
        run: |
          node -v
          yarn -v

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn static-generate
        env:
          VITE_CONFIG_ENV: ${{ vars.VITE_CONFIG_ENV }}

      - name: Static generate with timeout
        run: timeout 2m yarn static-generate
        env:
          VITE_CONFIG_ENV: ${{ vars.VITE_CONFIG_ENV }}

      - name: Cleanup lingering preview servers on port 4173
        run: |
          echo "Killing processes on port 4173"
          lsof -ti tcp:4173 | xargs -r kill -9 || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          clean: true
          cname: sensors.social

      - name: Set commit output
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
